### ISSUE TITLE
getPrice instead of priceOracle for oustandingVolume calculation in arbitration process

### ISSUE THREAD

**Issue by josojo** [gnosis/dx-react#121]
https://github.com/gnosis/dutch-exchange/blob/ddd0df69e767ecab1464d55dbbc94b6eca0bb1e6/contracts/DutchExchange.sol#L473

I guess we should use the getPrice ipo priceOracle function to calcualte the outstandingVolume

**Comment by hacker-DOM** [comment]
I think it's right. The idea was to use the price at 6 hours, which can't be done using getPrice. 

Even if we go a step further:
- what if the smaller auction's price dropped so that inflating its buyVolume "overbuys"? (A specific case would be the smaller auction clearing fully with time in the meantime.) not a bug, it will just clear as if it was arbitrated at the 6-hour mark
- what if the larger auction's price dropped so that inflating its buyVolume overbuys? *Thinking about it now*

Anyways, I'll add comments to make all that clear.

**Comment by hacker-DOM** [comment]
Re *thinking*: I'm not sure this is even possible. But even if it is, it shouldn't break nothing. Obviously the next buyOrder will clear the auction with 0 added amount, and it will clear at the price that it was supposed to clear, abstracting away the asynchronicity of blockchain. Right?
